name: production

services:
  go-service:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: runner-production
    environment:
      PORT: 8080
      POSTGRES_CONNSTR: postgres://postgres:s3cr3t@postgresql:5432/postgres
    networks:
      - go-service-network
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: s3cr3t
    healthcheck:
      test: ["CMD-SHELL", "psql -U 'postgres' -c '\\q'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5435:5432

networks:
  go-service-network:
    driver: bridge
