run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
  concurrency: 4

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
    - godox
    - stylecheck
    - exportloopref

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
        allow:
          - $gostd
          - golang.org/x/net/http/httpguts
          - google.golang.org/grpc
          - google.golang.org/grpc/reflection
          - google.golang.org/grpc/status
          - github.com/eser/ajan
          - github.com/eser/go-service
          - github.com/oklog/ulid/v2
          - github.com/go-playground/validator/v10
          - github.com/stretchr/testify
          - github.com/go-faker/faker/v4
          - github.com/getkin/kin-openapi/openapi3
          - github.com/golang-jwt/jwt/v5
          - github.com/prometheus/client_golang/prometheus
          - github.com/pressly/goose/v3
          - github.com/lib/pq
          - github.com/spf13/cobra
  revive:
    # enable-all-rules: true
    ignore-generated-header: true
    severity: warning
    rules:
      - name: var-naming
        disabled: true
        arguments: []
      # - name: exported
      #   severity: warning
      # - name: error-return
      #   severity: warning
      # - name: error-naming
      #   severity: warning
      # - name: if-return
      #   severity: warning
      # - name: var-naming
      #   severity: warning
      # - name: var-declaration
      #   severity: warning
      # - name: receiver-naming
      #   severity: warning
      # - name: errorf
      #   severity: warning
      # - name: empty-block
      #   severity: warning
      # - name: unused-parameter
      #   severity: warning
      # - name: unreachable-code
      #   severity: warning
      # - name: redefines-builtin-id
      #   severity: warning
      # - name: superfluous-else
      #   severity: warning
      # - name: unexported-return
      #   severity: warning
      # - name: indent-error-flow
      #   severity: warning
      # - name: blank-imports
      #   severity: warning
      # - name: range
      #   severity: warning
      # - name: time-naming
      #   severity: warning
      # - name: context-as-argument
      #   severity: warning
      # - name: context-keys-type
      #   severity: warning
      # - name: indent-error-flow
      #   severity: warning

issues:
  fix: true
  exclude-use-default: false
  exclude-dirs:
    - ops
    - tmp
