// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	Id              string
	Kind            string
	Slug            string
	EventPictureUri sql.NullString
	Title           string
	Description     string
	TimeStart       time.Time
	TimeEnd         time.Time
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
	SeriesId        sql.NullString
	Status          string
	AttendanceUri   sql.NullString
	PublishedAt     sql.NullTime
}

type EventAttendance struct {
	Id        string
	Kind      string
	EventId   string
	ProfileId string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type EventSeries struct {
	Id              string
	Slug            string
	EventPictureUri sql.NullString
	Title           string
	Description     string
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type Profile struct {
	Id                string
	Kind              string
	Slug              string
	ProfilePictureUri sql.NullString
	Title             string
	Description       string
	ShowStories       bool
	ShowProjects      bool
	CreatedAt         time.Time
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
}

type ProfileMembership struct {
	Id        string
	Kind      string
	ProfileId string
	UserId    string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Question struct {
	Id            string
	UserId        string
	Content       string
	IsHidden      bool
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	AnsweredAt    sql.NullTime
	AnswerUri     sql.NullString
	IsAnonymous   bool
	AnswerKind    sql.NullString
	AnswerContent sql.NullString
}

type QuestionVote struct {
	Id         string
	QuestionId string
	UserId     string
	Score      int32
	CreatedAt  time.Time
}

type Session struct {
	Id                       string
	Status                   string
	OauthRequestState        string
	OauthRequestCodeVerifier string
	OauthRedirectUri         sql.NullString
	LoggedInUserId           sql.NullString
	LoggedInAt               sql.NullTime
	ExpiresAt                sql.NullTime
	CreatedAt                time.Time
	UpdatedAt                sql.NullTime
}

type Story struct {
	Id              string
	Kind            string
	Status          string
	IsFeatured      sql.NullBool
	Slug            string
	StoryPictureUri sql.NullString
	Title           string
	Description     string
	AuthorProfileId sql.NullString
	Content         sql.NullString
	PublishedAt     sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type User struct {
	Id                  string
	Kind                string
	Name                string
	Email               sql.NullString
	Phone               sql.NullString
	GithubHandle        sql.NullString
	XHandle             sql.NullString
	CreatedAt           time.Time
	UpdatedAt           sql.NullTime
	DeletedAt           sql.NullTime
	GithubRemoteId      sql.NullString
	XRemoteId           sql.NullString
	IndividualProfileId sql.NullString
}
