name: Feature Request
description: Suggest an idea or voice a concern.
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
projects: ["eser/golang-service-template"]
assignees:
  - eser
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. x.com/eser
    validations:
      required: false
  - type: textarea
    id: problem-statement
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem statement is.
      placeholder: Ex. I'm frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Describe the expectated behavior you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this form, you agree to follow our **Code of Conduct**.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
