// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"
)

type Event struct {
	Id              string         `json:"id"`
	Kind            string         `json:"kind"`
	Slug            string         `json:"slug"`
	EventPictureUri sql.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	TimeStart       time.Time      `json:"timeStart"`
	TimeEnd         time.Time      `json:"timeEnd"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
	SeriesId        sql.NullString `json:"seriesId"`
	Status          string         `json:"status"`
	AttendanceUri   sql.NullString `json:"attendanceUri"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
}

type EventAttendance struct {
	Id        string       `json:"id"`
	Kind      string       `json:"kind"`
	EventId   string       `json:"eventId"`
	ProfileId string       `json:"profileId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type EventSeries struct {
	Id              string         `json:"id"`
	Slug            string         `json:"slug"`
	EventPictureUri sql.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type Profile struct {
	Id                string         `json:"id"`
	Kind              string         `json:"kind"`
	Slug              string         `json:"slug"`
	ProfilePictureUri sql.NullString `json:"profilePictureUri"`
	Title             string         `json:"title"`
	Description       string         `json:"description"`
	ShowStories       bool           `json:"showStories"`
	ShowProjects      bool           `json:"showProjects"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         sql.NullTime   `json:"updatedAt"`
	DeletedAt         sql.NullTime   `json:"deletedAt"`
}

type ProfileMembership struct {
	Id        string       `json:"id"`
	Kind      string       `json:"kind"`
	ProfileId string       `json:"profileId"`
	UserId    string       `json:"userId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type Question struct {
	Id            string         `json:"id"`
	UserId        string         `json:"userId"`
	Content       string         `json:"content"`
	IsHidden      bool           `json:"isHidden"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     sql.NullTime   `json:"updatedAt"`
	DeletedAt     sql.NullTime   `json:"deletedAt"`
	AnsweredAt    sql.NullTime   `json:"answeredAt"`
	AnswerUri     sql.NullString `json:"answerUri"`
	IsAnonymous   bool           `json:"isAnonymous"`
	AnswerKind    sql.NullString `json:"answerKind"`
	AnswerContent sql.NullString `json:"answerContent"`
}

type QuestionVote struct {
	Id         string    `json:"id"`
	QuestionId string    `json:"questionId"`
	UserId     string    `json:"userId"`
	Score      int32     `json:"score"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	Id                       string         `json:"id"`
	Status                   string         `json:"status"`
	OauthRequestState        string         `json:"oauthRequestState"`
	OauthRequestCodeVerifier string         `json:"oauthRequestCodeVerifier"`
	OauthRedirectUri         sql.NullString `json:"oauthRedirectUri"`
	LoggedInUserId           sql.NullString `json:"loggedInUserId"`
	LoggedInAt               sql.NullTime   `json:"loggedInAt"`
	ExpiresAt                sql.NullTime   `json:"expiresAt"`
	CreatedAt                time.Time      `json:"createdAt"`
	UpdatedAt                sql.NullTime   `json:"updatedAt"`
}

type Story struct {
	Id              string         `json:"id"`
	Kind            string         `json:"kind"`
	Status          string         `json:"status"`
	IsFeatured      sql.NullBool   `json:"isFeatured"`
	Slug            string         `json:"slug"`
	StoryPictureUri sql.NullString `json:"storyPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	AuthorProfileId sql.NullString `json:"authorProfileId"`
	Content         sql.NullString `json:"content"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type User struct {
	Id                  string         `json:"id"`
	Kind                string         `json:"kind"`
	Name                string         `json:"name"`
	Email               sql.NullString `json:"email"`
	Phone               sql.NullString `json:"phone"`
	GithubHandle        sql.NullString `json:"githubHandle"`
	XHandle             sql.NullString `json:"xHandle"`
	CreatedAt           time.Time      `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
	DeletedAt           sql.NullTime   `json:"deletedAt"`
	GithubRemoteId      sql.NullString `json:"githubRemoteId"`
	XRemoteId           sql.NullString `json:"xRemoteId"`
	IndividualProfileId sql.NullString `json:"individualProfileId"`
}
