global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "identitysvc"
    static_configs:
      - targets: ["identitysvc:8080"]
