global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "samplehttp"
    static_configs:
      - targets: ["samplehttp:8080"]
