// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dmls.sql

package data

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
insert into "user" (id, name, email, phone, github_remote_id, github_handle, x_remote_id, x_handle)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, kind, name, email, phone, individual_profile_id, github_remote_id, github_handle, x_remote_id, x_handle, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Id             string         `json:"id"`
	Name           string         `json:"name"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	GithubRemoteId sql.NullString `json:"githubRemoteId"`
	GithubHandle   sql.NullString `json:"githubHandle"`
	XRemoteId      sql.NullString `json:"xRemoteId"`
	XHandle        sql.NullString `json:"xHandle"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Id,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.GithubRemoteId,
		arg.GithubHandle,
		arg.XRemoteId,
		arg.XHandle,
	)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.IndividualProfileId,
		&i.GithubRemoteId,
		&i.GithubHandle,
		&i.XRemoteId,
		&i.XHandle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execresult
delete from "user"
where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getUserByGithubRemoteId = `-- name: GetUserByGithubRemoteId :one
select id, kind, name, email, phone, individual_profile_id, github_remote_id, github_handle, x_remote_id, x_handle, created_at, updated_at, deleted_at from "user"
where github_remote_id = $1
`

func (q *Queries) GetUserByGithubRemoteId(ctx context.Context, githubRemoteID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGithubRemoteId, githubRemoteID)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.IndividualProfileId,
		&i.GithubRemoteId,
		&i.GithubHandle,
		&i.XRemoteId,
		&i.XHandle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, kind, name, email, phone, individual_profile_id, github_remote_id, github_handle, x_remote_id, x_handle, created_at, updated_at, deleted_at from "user"
where id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.IndividualProfileId,
		&i.GithubRemoteId,
		&i.GithubHandle,
		&i.XRemoteId,
		&i.XHandle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, kind, name, email, phone, individual_profile_id, github_remote_id, github_handle, x_remote_id, x_handle, created_at, updated_at, deleted_at from "user"
where id > $1 and deleted_at is null
order by id
limit $2
`

type ListUsersParams struct {
	Offset string `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Id,
			&i.Kind,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.IndividualProfileId,
			&i.GithubRemoteId,
			&i.GithubHandle,
			&i.XRemoteId,
			&i.XHandle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :execresult
update "user"
set name = $2
where id = $1
`

type UpdateUserParams struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser, arg.Id, arg.Name)
}

const upsertUserByGithubRemoteId = `-- name: UpsertUserByGithubRemoteId :one
insert into "user" (id, name, email, phone, github_remote_id, github_handle, x_remote_id, x_handle)
values ($1, $2, $3, $4, $5, $6, $7, $8)
on conflict (github_remote_id)
where deleted_at is null
do update set
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  github_handle = EXCLUDED.github_handle,
  x_remote_id = EXCLUDED.x_remote_id,
  x_handle = EXCLUDED.x_handle,
  updated_at = now()
returning id, kind, name, email, phone, individual_profile_id, github_remote_id, github_handle, x_remote_id, x_handle, created_at, updated_at, deleted_at
`

type UpsertUserByGithubRemoteIdParams struct {
	Id             string         `json:"id"`
	Name           string         `json:"name"`
	Email          sql.NullString `json:"email"`
	Phone          sql.NullString `json:"phone"`
	GithubRemoteId sql.NullString `json:"githubRemoteId"`
	GithubHandle   sql.NullString `json:"githubHandle"`
	XRemoteId      sql.NullString `json:"xRemoteId"`
	XHandle        sql.NullString `json:"xHandle"`
}

func (q *Queries) UpsertUserByGithubRemoteId(ctx context.Context, arg UpsertUserByGithubRemoteIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByGithubRemoteId,
		arg.Id,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.GithubRemoteId,
		arg.GithubHandle,
		arg.XRemoteId,
		arg.XHandle,
	)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.IndividualProfileId,
		&i.GithubRemoteId,
		&i.GithubHandle,
		&i.XRemoteId,
		&i.XHandle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
