// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"

	"github.com/eser/go-service/pkg/bliss/lib"
)

type Event struct {
	Id              string         `json:"id"`
	Kind            string         `json:"kind"`
	Status          string         `json:"status"`
	SeriesId        sql.NullString `json:"seriesId"`
	Slug            string         `json:"slug"`
	EventPictureUri lib.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	AttendanceUri   lib.NullString `json:"attendanceUri"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
	TimeStart       time.Time      `json:"timeStart"`
	TimeEnd         time.Time      `json:"timeEnd"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type EventAttendance struct {
	Id        string       `json:"id"`
	Kind      string       `json:"kind"`
	EventId   string       `json:"eventId"`
	ProfileId string       `json:"profileId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type EventSeries struct {
	Id              string         `json:"id"`
	Slug            string         `json:"slug"`
	EventPictureUri lib.NullString `json:"eventPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type Profile struct {
	Id                string         `json:"id"`
	Kind              string         `json:"kind"`
	Slug              string         `json:"slug"`
	ProfilePictureUri lib.NullString `json:"profilePictureUri"`
	Title             string         `json:"title"`
	Description       string         `json:"description"`
	ShowStories       bool           `json:"showStories"`
	ShowProjects      bool           `json:"showProjects"`
	CreatedAt         time.Time      `json:"createdAt"`
	UpdatedAt         sql.NullTime   `json:"updatedAt"`
	DeletedAt         sql.NullTime   `json:"deletedAt"`
}

type ProfileMembership struct {
	Id        string       `json:"id"`
	Kind      string       `json:"kind"`
	ProfileId string       `json:"profileId"`
	UserId    string       `json:"userId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
	DeletedAt sql.NullTime `json:"deletedAt"`
}

type Question struct {
	Id            string         `json:"id"`
	UserId        string         `json:"userId"`
	Content       string         `json:"content"`
	AnswerKind    lib.NullString `json:"answerKind"`
	AnswerContent lib.NullString `json:"answerContent"`
	AnswerUri     lib.NullString `json:"answerUri"`
	AnsweredAt    sql.NullTime   `json:"answeredAt"`
	IsAnonymous   bool           `json:"isAnonymous"`
	IsHidden      bool           `json:"isHidden"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     sql.NullTime   `json:"updatedAt"`
	DeletedAt     sql.NullTime   `json:"deletedAt"`
}

type QuestionVote struct {
	Id         string    `json:"id"`
	QuestionId string    `json:"questionId"`
	UserId     string    `json:"userId"`
	Score      int32     `json:"score"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Session struct {
	Id                       string         `json:"id"`
	Status                   string         `json:"status"`
	OauthRequestState        string         `json:"oauthRequestState"`
	OauthRequestCodeVerifier string         `json:"oauthRequestCodeVerifier"`
	OauthRedirectUri         lib.NullString `json:"oauthRedirectUri"`
	LoggedInUserId           sql.NullString `json:"loggedInUserId"`
	LoggedInAt               sql.NullTime   `json:"loggedInAt"`
	ExpiresAt                sql.NullTime   `json:"expiresAt"`
	CreatedAt                time.Time      `json:"createdAt"`
	UpdatedAt                sql.NullTime   `json:"updatedAt"`
}

type Story struct {
	Id              string         `json:"id"`
	Kind            string         `json:"kind"`
	Status          string         `json:"status"`
	IsFeatured      sql.NullBool   `json:"isFeatured"`
	Slug            string         `json:"slug"`
	StoryPictureUri lib.NullString `json:"storyPictureUri"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	AuthorProfileId sql.NullString `json:"authorProfileId"`
	Summary         string         `json:"summary"`
	Content         string         `json:"content"`
	PublishedAt     sql.NullTime   `json:"publishedAt"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       sql.NullTime   `json:"updatedAt"`
	DeletedAt       sql.NullTime   `json:"deletedAt"`
}

type User struct {
	Id                  string         `json:"id"`
	Kind                string         `json:"kind"`
	Name                string         `json:"name"`
	Email               lib.NullString `json:"email"`
	Phone               lib.NullString `json:"phone"`
	IndividualProfileId sql.NullString `json:"individualProfileId"`
	GithubRemoteId      lib.NullString `json:"githubRemoteId"`
	GithubHandle        lib.NullString `json:"githubHandle"`
	XRemoteId           lib.NullString `json:"xRemoteId"`
	XHandle             lib.NullString `json:"xHandle"`
	CreatedAt           time.Time      `json:"createdAt"`
	UpdatedAt           sql.NullTime   `json:"updatedAt"`
	DeletedAt           sql.NullTime   `json:"deletedAt"`
}
