name: development

services:
  sample:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: runner-development
    develop:
      watch:
        - action: sync+restart
          path: ../
          target: /app/
          ignore:
            - .*
            - tmp/
    environment:
      PORT: 8080
      POSTGRES_CONNSTR: postgres://postgres:s3cr3t@postgresql:5432/postgres
    networks:
      - acik-io-network
    ports:
      - 8080:8080
    depends_on:
      fluentd:
        condition: service_healthy
      postgres:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: sample

  postgres:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: s3cr3t
    healthcheck:
      test: ["CMD-SHELL", "psql -U 'postgres' -c '\\q'"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - acik-io-network
    ports:
      - 5432:5432
    depends_on:
      fluentd:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: "true"
        tag: postgres

  prometheus:
    image: prom/prometheus:latest
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    networks:
      - acik-io-network
    ports:
      - 9090:9090

  fluentd:
    build:
      context: ./resources/fluentd/
    environment:
      FLUENTD_CONF: "fluent.conf"
    configs:
      - source: fluentd-config
        target: /fluentd/etc/fluent.conf
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "24224"]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      # - host_logs:/var/log
      # Needed for journald log ingestion:
      - /etc/machine-id:/etc/machine-id
      - /dev/log:/dev/log
      - /var/run/systemd/journal/:/var/run/systemd/journal/
    networks:
      - acik-io-network
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      loki:
        condition: service_started
    logging:
      options:
        tag: infra.monitoring

  loki:
    image: grafana/loki:main
    user: "0"
    configs:
      - source: loki-config
        target: /etc/loki/local_config.yaml
    volumes:
      - loki-data:/var/loki
    command: -config.file=/etc/loki/local_config.yaml
    networks:
      - acik-io-network
    ports:
      - 3100:3100

  grafana:
    image: grafana/grafana:main
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      # - grafana-data:/var/lib/grafana
      - ./resources/grafana/provisioning:/etc/grafana/provisioning
      - ./resources/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - acik-io-network
    ports:
      - 3000:3000

configs:
  prometheus-config:
    file: ./resources/prometheus/prometheus.yml
  fluentd-config:
    file: ./resources/fluentd/fluentd.conf
  loki-config:
    file: ./resources/loki/local_config.yaml

volumes:
  postgres-data:
  # grafana-data:
  loki-data:

networks:
  acik-io-network:
    driver: bridge
